/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

	struct DataPacket
	{
	char dataA;
	int dataB;
	short dataC;
	char dataD;
	};//__attribute__((packed));

	int main(void)
	{
		struct DataPacket data;
		uint8_t *ptr;
		ptr = (uint8_t*)&data;

		//struct DataPacket data;
		data.dataA = 0xFF;
		data.dataB = 0x4F4C4C45;
		data.dataC = 0x48CD;
		data.dataD = 0x45;
	}


